import Link from "next/link";
import { createTemplateAction } from "@/app/actions/templates";
import { SubmitButton } from "@/components/submit-button";

export const metadata = { title: "Novo modelo" };
export default async function NewTemplatePage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const query = await searchParams;
  return <><header className="page-header"><div><p className="eyebrow">MODELO PARTICULAR</p><h1>Novo modelo</h1><p>Crie um texto reutilizável com variáveis no formato {"{{campo}}"}.</p></div><Link className="button button-secondary" href="/biblioteca">Cancelar</Link></header>{query.error && <div className="notice notice-error">{query.error}</div>}<form className="card form-card form-card-wide" action={createTemplateAction}><div className="form-grid"><label className="field"><span>Título</span><input className="input" name="title" required /></label><label className="field"><span>Especialidade</span><input className="input" name="specialty" defaultValue="Geral" /></label><label className="field"><span>Categoria</span><select className="select" name="category" defaultValue="petition"><option value="petition">Petição / manifestação</option><option value="report">Laudo</option><option value="opinion">Parecer</option><option value="checklist">Checklist</option><option value="technical_block">Bloco técnico</option></select></label><label className="field"><span>Tipo interno</span><input className="input" name="document_type" defaultValue="personalizado" /></label><label className="field full"><span>Descrição</span><input className="input" name="description" /></label><label className="field full"><span>Referências normativas — uma por linha</span><textarea className="textarea textarea-small" name="legal_basis" /></label><label className="field full"><span>Conteúdo do modelo</span><textarea className="document-editor document-editor-medium" name="body" placeholder={"PROCESSO Nº {{numero_processo}}\n\nEscreva o conteúdo..."} required /></label></div><div className="form-actions"><Link className="button button-secondary" href="/biblioteca">Voltar</Link><SubmitButton pendingText="Criando...">Criar modelo</SubmitButton></div></form></>;
}
